#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt -y update
sudo apt -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\nerror_page 404 \/404.html;\nrewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

sudo service nginx restart