#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

MYFILE="/var/run/holbertonscript.pid"
sudo touch $MYFILE
echo $$ > $MYFILE

while true
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"; sudo rm $MYFILE' SIGTERM
    	trap 'echo "Y U no love me?!"' SIGINT
    	trap 'sudo rm $MYFILE' SIGQUIT
	sleep 2
done