#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.
#   Format: OCCURENCE_NUMBER IP HTTP_CODE
#   Ordered from the greatest to the lowest number of occurrences
#   Use awk

awk '{ print "%s %s\n", $1, $9 }' "apache-access.log" | sort | uniq -c | sort -nr