#!/usr/bin/env bash
#Install ufw firewall and block all incoming traffic
#except ssh, http, https

sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable